[package]
name = "modern-cv"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "lib.typ"
authors = ["Paul Tsouchlos <https://github.com/DeveloperPaul123>"]
license = "MIT"
description = "A modern resume based on the Awesome-CV Latex template."
keywords = ["CV", "Resume", "Minimalistic", "Professional", "Modern"]
categories = ["cv"]
disciplines = []
exclude = ["resume-documentation*", "scripts*"]

[template]
path = "template"
entrypoint = "resume.typ"
thumbnail = "resume.png"